# Generated by Django 5.0.6 on 2025-01-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='position',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=20),
        ),
    ]
